.PHONY: init fmt validate plan setup destroy

init:
	@../../scripts/project.sh init firewall

fmt:
	@../../scripts/project.sh fmt firewall

validate:
	@../../scripts/project.sh validate firewall

plan:
	@../../scripts/project.sh plan firewall

setup:
	@../../scripts/project.sh setup firewall

destroy:
	@../../scripts/project.sh destroy firewall
